
import { Product, Ticket, MarketPrice, Language, CropOffer, InputOrder } from './types';

// Ethiopian Context Images - High Quality / "AI Enhanced" Look
const IMG_TEFF = "https://images.unsplash.com/photo-1586771107445-d3ca888129ff?q=80&w=800&auto=format&fit=crop"; // Red/Brown Teff Grains
const IMG_COFFEE = "https://images.unsplash.com/photo-1524350876685-274059332603?q=80&w=800&auto=format&fit=crop"; // Vibrant coffee cherries
const IMG_MAIZE = "https://images.unsplash.com/photo-1551754655-cd27e38d2076?q=80&w=800&auto=format&fit=crop"; // Detailed Maize Cobs/Seeds
const IMG_FERT = "https://plus.unsplash.com/premium_photo-1661962692059-55d5a4319814?q=80&w=800&auto=format&fit=crop"; // Professional packaging
const IMG_TOOL = "https://images.unsplash.com/photo-1627916607164-7b7f24043995?q=80&w=800&auto=format&fit=crop"; // Garden Tool / Hoe on Grass
const IMG_WHEAT = "https://images.unsplash.com/photo-1501430654243-c934cec2e1c0?q=80&w=800&auto=format&fit=crop"; // Golden Wheat Field
const IMG_SPRAYER = "https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?q=80&w=800&auto=format&fit=crop"; // Clean equipment

export const ETHIOPIAN_NAMES = [
  "Abebe Kebede", "Almaz Ayana", "Bekele Tadesse", "Chaltu Regasa", "Dawit Mulatu",
  "Etenesh Diro", "Fikru Tefera", "Genet Yalew", "Hailemariam Desalegn", "Kassa Hailu",
  "Lemlem Hailu", "Marta Yota", "Nardos Bekele", "Robel Teklemariam", "Solomon Deksisa",
  "Tirhas Gebre", "Yomif Kejelcha", "Zenebech Tola", "Girma Wolde", "Hirut Mesfin"
];

export const INITIAL_PRODUCTS: Product[] = [
  { id: '1', name: 'Red Teff Seeds (Magna)', category: 'Seeds', price: 8500, stock: 50, unit: 'quintal', image: IMG_TEFF },
  { id: '2', name: 'DAP Fertilizer', category: 'Fertilizer', price: 4500, stock: 120, unit: '50kg', image: IMG_FERT },
  { id: '3', name: 'Quality Coffee Seedlings', category: 'Seeds', price: 25, stock: 500, unit: 'seedling', image: IMG_COFFEE },
  { id: '4', name: 'Hybrid Maize BH-661', category: 'Seeds', price: 3200, stock: 80, unit: '25kg', image: IMG_MAIZE },
  { id: '6', name: 'Wheat Seeds (Kingbird)', category: 'Seeds', price: 3800, stock: 60, unit: 'quintal', image: IMG_WHEAT },
  { id: '7', name: 'Knapsack Sprayer (16L)', category: 'Tools', price: 1500, stock: 25, unit: 'pcs', image: IMG_SPRAYER },
];

export const INITIAL_PRICES: MarketPrice[] = [
  { crop: 'Teff (White)', pricePerKg: 120, trend: 'up', lastUpdated: new Date().toISOString() },
  { crop: 'Coffee (Jimma)', pricePerKg: 1300, trend: 'stable', lastUpdated: new Date().toISOString() },
  { crop: 'Maize', pricePerKg: 55, trend: 'down', lastUpdated: new Date().toISOString() },
  { crop: 'Wheat', pricePerKg: 85, trend: 'up', lastUpdated: new Date().toISOString() },
];

export const INITIAL_TICKETS: Ticket[] = [
  { 
    id: 'T-1001', 
    farmerName: 'Abebe Bikila', 
    phoneNumber: '+251 911 234 567', 
    issue: 'My Teff crop is showing signs of rust. Need advice immediately.', 
    status: 'Open', 
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    priority: 'High'
  },
  { 
    id: 'T-1002', 
    farmerName: 'Almaz Ayana', 
    phoneNumber: '+251 922 876 543', 
    issue: 'When will the new batch of DAP fertilizer arrive?', 
    status: 'In Progress', 
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    priority: 'Medium'
  },
];

export const INITIAL_OFFERS: CropOffer[] = [
  {
    id: 'O-5501',
    farmerName: 'Derartu Tulu',
    crop: 'Coffee (Jimma)',
    quantity: 15, // Quintals
    status: 'Pending',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'O-5502',
    farmerName: 'Kenenisa Bekele',
    crop: 'Teff (White)',
    quantity: 40,
    status: 'Pending',
    timestamp: new Date(Date.now() - 14000000).toISOString(),
  },
  {
    id: 'O-5503',
    farmerName: 'Tirunesh Dibaba',
    crop: 'Maize',
    quantity: 100,
    status: 'Accepted',
    timestamp: new Date(Date.now() - 40000000).toISOString(),
  },
  {
    id: 'O-5504',
    farmerName: 'Haile Gebrselassie',
    crop: 'Wheat',
    quantity: 60,
    status: 'Pending',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'O-5505',
    farmerName: 'Girma Wolde',
    crop: 'Coffee (Jimma)',
    quantity: 12,
    status: 'Pending',
    timestamp: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'O-5506',
    farmerName: 'Hirut Mesfin',
    crop: 'Maize',
    quantity: 85,
    status: 'Pending',
    timestamp: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: 'O-5507',
    farmerName: 'Bekele Tadesse',
    crop: 'Teff (White)',
    quantity: 25,
    status: 'Pending',
    timestamp: new Date(Date.now() - 43200000).toISOString(),
  },
  {
    id: 'O-5508',
    farmerName: 'Meseret Defar',
    crop: 'Teff (White)',
    quantity: 18,
    status: 'Pending',
    timestamp: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: 'O-5509',
    farmerName: 'Berhane Adere',
    crop: 'Wheat',
    quantity: 45,
    status: 'Pending',
    timestamp: new Date(Date.now() - 200000).toISOString(),
  },
  {
    id: 'O-5510',
    farmerName: 'Sileshi Sihine',
    crop: 'Coffee (Jimma)',
    quantity: 8,
    status: 'Pending',
    timestamp: new Date(Date.now() - 100000).toISOString(),
  }
];

export const INITIAL_ORDERS: InputOrder[] = [
  {
    id: 'OR-901',
    farmerName: 'Mamo Wolde',
    productName: 'DAP Fertilizer',
    quantity: 2,
    totalPrice: 9000,
    status: 'Pending',
    timestamp: new Date(Date.now() - 10000000).toISOString(),
  }
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    app_name: 'AgriConnect Ethiopia',
    welcome: 'Welcome',
    inventory: 'My Store',
    requests: 'Support Tickets',
    buying: 'Marketplace',
    orders: 'Input Orders',
    market_prices: 'Market Prices',
    history: 'History',
    search: 'Search...',
    add_product: 'Add Input Stock',
    stock_level: 'In Stock',
    price: 'Price',
    last_updated: 'Last updated',
    trend: 'Trend',
    upload_image: 'Upload Image',
    farmer: 'Farmer',
    dealer: 'Dealer',
    agent: 'Call Center',
    select_persona: 'Select Persona',
    type_message: 'Sell Teff, Buy DAP...',
    chat_subtitle: 'Chat to Sell Produce or Buy Inputs',
    ussd_prompt: 'Type *707#',
    stock_updated: 'Stock updated',
    price_updated: 'Price updated',
    sell_produce: 'Sell Produce',
    buy_inputs: 'Buy Inputs',
    quantity_quintal: 'Qty (Quintal)',
    estimated_value: 'Est. Value',
    accept: 'Buy Crop',
    reject: 'Ignore',
    status: 'Status',
    fulfill: 'Fulfill Order',
    sms_accepted: 'DEAL ALERT: Your offer for {qty} Qtl of {crop} has been ACCEPTED by Dealer. Total: {total} ETB. Please call Dealer: 0911-55-44-22.',
    sms_order_fulfilled: 'ORDER READY: Your order for {qty}x {product} is ready for pickup. Total: {total} ETB. Call Dealer: 0911-55-44-22 to arrange transport.',
    // Login & Reg
    login_title: 'Dealer Portal',
    login_subtitle: 'AgriConnect Ethiopia',
    username: 'Username',
    password: 'Password',
    sign_in: 'Sign In',
    signing_in: 'Signing In...',
    create_account: 'Create Account',
    dont_have_account: "Don't have an account?",
    full_name: 'Full Name',
    store_name: 'Store Name',
    back_login: 'Back to Login',
    demo_creds: 'Demo Credentials',
    success: 'Success!',
    redirecting: 'Redirecting to login...',
    invalid_creds: 'Invalid credentials. Try admin / password',
    fields_required: 'All fields are required',
    // Phone UI
    messages: 'Messages',
    no_messages: 'No Messages',
    menu: 'MENU',
    back: 'BACK',
    clear: 'CLEAR',
    cancel: 'CANCEL',
    select: 'SELECT',
    input: 'Input',
    loading: 'Loading...',
    // Dealer Dashboard Specific
    marketplace_overview: 'Marketplace Overview',
    marketplace_desc: 'Connect directly with local farmers. Acquire premium crops at fair market rates to restock your inventory effectively.',
    view_reports: 'View Reports',
    manage_settings: 'Manage Settings',
    new_offers: 'New Offers',
    acquired: 'Acquired',
    pending_offers: 'Pending Farmer Offers',
    pending: 'Pending',
    no_pending_offers: 'No pending offers at the moment.',
    quantity: 'Quantity',
    value: 'Value',
    ignore: 'Ignore',
    accept_offer: 'Accept Offer',
    pending_orders: 'Pending Orders',
    total: 'Total',
    reject_order: 'Reject Order',
    no_orders_yet: 'No input orders yet.',
    unit: 'Unit',
    clear_log: 'Clear Log',
    no_activity: 'No recent activity recorded.',
    dealer_portal: 'Dealer Portal',
    logout: 'Logout',
    green_agro: 'GreenAgro',
    system_alert: 'ALERT: Heavy rains expected in Oromia region. Secure Teff harvest.',
    reports_title: 'Reports',
    sales_summary: 'Sales Summary',
    top_products: 'Top Products',
    settings_title: 'Settings',
    store_profile: 'Store Profile',
    notifications: 'Notifications',
    enable_sms_alerts: 'Enable SMS Alerts',
    save_changes: 'Save Changes'
  },
  am: {
    app_name: 'አግሪ-ኮኔክት ኢትዮጵያ',
    welcome: 'እንኳን ደህና መጡ',
    inventory: 'የእቃ ክምችት',
    requests: 'የድጋፍ ጥያቄዎች',
    buying: 'የገበያ ስፍራ',
    orders: 'የግብዓት ትዕዛዞች',
    market_prices: 'የገበያ ዋጋ',
    history: 'የስራ እንቅስቃሴ',
    search: 'ፈልግ...',
    add_product: 'ግብዓት ጨምር',
    stock_level: 'ያለ እቃ',
    price: 'ዋጋ',
    last_updated: 'መጨረሻ የተሻሻለው',
    trend: 'ለውጥ',
    upload_image: 'ፎቶ ጫን',
    farmer: 'ገበሬ',
    dealer: 'ነጋዴ',
    agent: 'የደንበኛ አገልግሎት',
    select_persona: 'ሚና ይምረጡ',
    type_message: 'ምርት ለመሸጥ, ግብዓት ለመግዛት...',
    chat_subtitle: 'ምርት ለመሸጥ ወይም ለመግዛት ይጻፉ',
    ussd_prompt: '*707# ይደውሉ',
    stock_updated: 'ክምችት ተሻሽሏል',
    price_updated: 'ዋጋ ተሻሽሏል',
    sell_produce: 'ምርት ለመሸጥ',
    buy_inputs: 'ግብዓት ለመግዛት',
    quantity_quintal: 'መጠን (ኩንታል)',
    estimated_value: 'ግምታዊ ዋጋ',
    accept: 'ግዛ',
    reject: 'አትቀበል',
    status: 'ሁኔታ',
    fulfill: 'ትዕዛዝ አሟላ',
    sms_accepted: 'የሽያጭ ማስታወቂያ: ለ{qty} ኩንታል {crop} ያቀረቡት ዋጋ በነጋዴው ተቀባይነት አግኝቷል። ጠቅላላ: {total} ብር። ለተጨማሪ: 0911-55-44-22 ይደውሉ።',
    sms_order_fulfilled: 'ትዕዛዝ ዝግጁ ነው: ያዘዙት {qty}x {product} ተዘጋጅቷል። ጠቅላላ: {total} ብር። ለመውሰድ: 0911-55-44-22 ይደውሉ።',
    login_title: 'የነጋዴ መግቢያ',
    login_subtitle: 'አግሪ-ኮኔክት ኢትዮጵያ',
    username: 'መጠቀሚያ ስም',
    password: 'የይለፍ ቃል',
    sign_in: 'ግባ',
    signing_in: 'በመግባት ላይ...',
    create_account: 'መለያ ይፍጠሩ',
    dont_have_account: 'መለያ የለዎትም?',
    full_name: 'ሙሉ ስም',
    store_name: 'የሱቅ ስም',
    back_login: 'ወደ መግቢያ ተመለስ',
    demo_creds: 'የሙከራ መለያ',
    success: 'ተሳክቷል!',
    redirecting: 'ወደ መግቢያ በመውሰድ ላይ...',
    invalid_creds: 'የተሳሳተ መረጃ። admin / password ይሞክሩ',
    fields_required: 'ሁሉም መረጃዎች ያስፈልጋሉ',
    messages: 'መልዕክቶች',
    no_messages: 'ምንም መልዕክት የለም',
    menu: 'ማውጫ',
    back: 'ተመለስ',
    clear: 'አጥፋ',
    cancel: 'ተው',
    select: 'ምረጥ',
    input: 'ምላሽ',
    loading: 'በመጫን ላይ...',
    marketplace_overview: 'የገበያ አጠቃላይ እይታ',
    marketplace_desc: 'ከአካባቢው ገበሬዎች ጋር በቀጥታ ይገናኙ። ምርጥ ሰብሎችን በተመጣጣኝ ዋጋ በመግዛት ክምችትዎን ያሳድጉ።',
    view_reports: 'ሪፖርት ይመልከቱ',
    manage_settings: 'ቅንብሮች',
    new_offers: 'አዲስ ቅናሾች',
    acquired: 'የተገዛ',
    pending_offers: 'በመጠባበቅ ላይ ያሉ',
    pending: 'በመጠባበቅ ላይ',
    no_pending_offers: 'ምንም የሽያጭ ጥያቄ የለም።',
    quantity: 'መጠን',
    value: 'ዋጋ',
    ignore: 'አለፍ',
    accept_offer: 'ተቀበል',
    pending_orders: 'የግብዓት ትዕዛዞች',
    total: 'ጠቅላላ',
    reject_order: 'ሰረዝ',
    no_orders_yet: 'ምንም ትዕዛዝ የለም።',
    unit: 'መለኪያ',
    clear_log: 'ታሪክ አጽዳ',
    no_activity: 'ምንም እንቅስቃሴ የለም።',
    dealer_portal: 'የነጋዴ መግቢያ',
    logout: 'ውጣ',
    green_agro: 'ግሪን አግሮ',
    system_alert: 'ማሳሰቢያ: በኦሮሚያ ክልል ከባድ ዝናብ ስለሚጠበቅ ምርትዎን በጥንቃቄ ይያዙ።',
    reports_title: 'ሪፖርቶች',
    sales_summary: 'የሽያጭ ማጠቃለያ',
    top_products: 'ተፈላጊ ምርቶች',
    settings_title: 'ቅንብሮች',
    store_profile: 'የሱቅ መገለጫ',
    notifications: 'ማስታወቂያዎች',
    enable_sms_alerts: 'የኤስኤምኤስ መልዕክት አብራ',
    save_changes: 'ለውጦችን አስቀምጥ'
  }
};
